/**
 * Stage look knobs. Desktop is the default budget (this game runs in a
 * computer browser). Mobile is a conservative fallback if we detect a phone.
 */
export type QualityPreset = 'desktop' | 'mobile'

function detectQualityPreset(): QualityPreset {
  if (typeof window === 'undefined' || typeof navigator === 'undefined') return 'desktop'
  const ua = navigator.userAgent || ''
  const phone = /Android|iPhone|iPod/i.test(ua) && !/iPad/i.test(ua)
  const coarse = window.matchMedia?.('(pointer: coarse)').matches ?? false
  if (phone && coarse && window.innerWidth < 900) return 'mobile'
  return 'desktop'
}

export const QUALITY_PRESET: QualityPreset = detectQualityPreset()

const DESKTOP = {
  quality: 'desktop' as const,
  ambient: 0.38,
  ambientColor: '#f4f8ff',
  hemi: 0.38,
  hemiSky: '#fff8f0',
  hemiGround: '#ffd2b8',
  key: 1.52,
  keyColor: '#fffaf6',
  keyPosition: [6.2, 7.2, 5.0] as [number, number, number],
  fillCool: 0.32,
  fillCoolColor: '#b8e4ff',
  fillWarm: 0.1,
  fillWarmColor: '#ffd8cc',
  rim: 0.36,
  rimColor: '#ffe8f4',
  rimPosition: [-4.2, 3.4, -5.2] as [number, number, number],
  footlightCount: 7,
  footlightIntensity: 2.85,
  footlightColor: '#ffc498',
  footlightAngle: 0.96,
  footlightPenumbra: 0.8,
  footlightDistance: 6.6,
  apronIntensity: 0.62,
  apronColor: '#ffd0a8',
  shadowMapSize: 2048,
  softShadows: true,
  softShadowSize: 16,
  softShadowSamples: 16,
  softShadowFocus: 0.6,
  dpr: [1, 2] as [number, number],
  exposure: 1.12,
  bloomThreshold: 0.88,
  bloomSmoothing: 0.42,
  bloomIntensity: 0.2,
  contactOpacity: 0.34,
  contactBlur: 1.7,
  contactResolution: 1024,
  contactFar: 3.6,
  contactColor: '#8a6cb4',
  ssao: true,
  ssaoIntensity: 0.32,
  ssaoRadius: 0.36,
  ssaoColor: '#8a6cb0',
  envResolution: 256,
  envIntensity: 0.4,
  roughness: 0.5,
  roughnessGlow: 0.42,
  clearcoat: 0.55,
  clearcoatGlow: 0.14,
  clearcoatRoughness: 0.26,
  sheen: 0.68,
  sheenRoughness: 0.5,
  envMapIntensity: 0.48,
  specularIntensity: 0.58,
  normalStrength: 0.28,
  bodySegments: 32,
  boxSmoothness: 5,
  glowDefault: 0.32,
  glowOrb: 0.38,
  glowLamp: 0.58,
  glowIcon: 0.28,
  glowStar: 0.3,
  glowFlower: 0.22,
}

const MOBILE = {
  quality: 'mobile' as const,
  ambient: 0.36,
  ambientColor: '#f4f8ff',
  hemi: 0.4,
  hemiSky: '#fff8f0',
  hemiGround: '#ffd2b8',
  key: 1.28,
  keyColor: '#fffaf6',
  keyPosition: [6.2, 7.2, 5.0] as [number, number, number],
  fillCool: 0.2,
  fillCoolColor: '#b8e4ff',
  fillWarm: 0.06,
  fillWarmColor: '#ffd8cc',
  rim: 0.14,
  rimColor: '#ffe8f4',
  rimPosition: [-4.2, 3.4, -5.2] as [number, number, number],
  footlightCount: 3,
  footlightIntensity: 2.45,
  footlightColor: '#ffc498',
  footlightAngle: 0.95,
  footlightPenumbra: 0.84,
  footlightDistance: 7.6,
  apronIntensity: 0.72,
  apronColor: '#ffd0a8',
  shadowMapSize: 512,
  softShadows: false,
  softShadowSize: 16,
  softShadowSamples: 8,
  softShadowFocus: 0.6,
  dpr: [1, 1.5] as [number, number],
  exposure: 1.1,
  bloomThreshold: 0.9,
  bloomSmoothing: 0.36,
  bloomIntensity: 0.2,
  contactOpacity: 0.32,
  contactBlur: 2.2,
  contactResolution: 256,
  contactFar: 3.2,
  contactColor: '#8a6cb4',
  ssao: false,
  ssaoIntensity: 0.4,
  ssaoRadius: 0.4,
  ssaoColor: '#7a5aa0',
  envResolution: 64,
  envIntensity: 0.26,
  roughness: 0.7,
  roughnessGlow: 0.5,
  clearcoat: 0.26,
  clearcoatGlow: 0.1,
  clearcoatRoughness: 0.48,
  sheen: 0.2,
  sheenRoughness: 0.8,
  envMapIntensity: 0.26,
  specularIntensity: 0.32,
  normalStrength: 0,
  bodySegments: 16,
  boxSmoothness: 3,
  glowDefault: 0.36,
  glowOrb: 0.42,
  glowLamp: 0.62,
  glowIcon: 0.32,
  glowStar: 0.34,
  glowFlower: 0.26,
}

export const STAGE_LOOK = QUALITY_PRESET === 'mobile' ? MOBILE : DESKTOP
