import type { CharacterId, CharacterLook } from '../types'

export const CHARACTERS: Record<CharacterId, CharacterLook> = {
  boogar: {
    name: 'Boogar',
    bodyColor: '#FF8C73',
    accentColor: '#2A012D',
    skinColor: '#FF8C73',
    limbColor: '#FF8C73',
    eyeColor: '#2A012D',
    toothColor: '#FFB6A0',
    clawColor: '#2A012D',
    featureColor: '#FFB6A0',
    height: 1.08,
    belly: 1.55,
    bodyForm: 'wide',
    limbStyle: 'thick',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'dot',
    eyeSpacing: 0.16,
    eyeSize: 0.028,
    eyeY: 0.1,
    mouthStyle: 'twoTeeth',
    browStyle: 'unibrow',
    features: ['bearEars', 'claws4'],
    tail: 'none',
    monobody: true,
    legLength: 0.14,
    armLength: 0.34,
  },
  ceval: {
    name: 'Ceval',
    bodyColor: '#F0C4A0',
    accentColor: '#551ABB',
    skinColor: '#F0C4A0',
    limbColor: '#551ABB',
    eyeColor: '#2A1238',
    scleraColor: '#FFF8F0',
    irisColor: '#551ABB',
    featureColor: '#4F9A52',
    height: 1.18,
    belly: 1.35,
    bodyForm: 'onion',
    limbStyle: 'wavy',
    armCount: 4,
    eyeCount: 1,
    eyeStyle: 'cyclops',
    eyeSpacing: 0,
    eyeSize: 0.11,
    eyeY: 0.04,
    mouthStyle: 'smile',
    browStyle: 'none',
    features: ['onionSprout', 'onionRidges'],
    tail: 'none',
    monobody: true,
    legLength: 0.28,
    armLength: 0.3,
  },
  dan: {
    name: 'Dan',
    bodyColor: '#6FA7A1',
    accentColor: '#FFD54F',
    skinColor: '#6FA7A1',
    limbColor: '#6FA7A1',
    eyeColor: '#1A1A1A',
    mouthColor: '#3B0D3D',
    clawColor: '#FF6B6B',
    featureColor: '#FF6B6B',
    height: 1.12,
    belly: 1.38,
    bodyForm: 'egg',
    limbStyle: 'stubby',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'dot',
    eyeSpacing: 0.14,
    eyeSize: 0.03,
    eyeY: 0.12,
    mouthStyle: 'smile',
    browStyle: 'none',
    features: ['bullHorns', 'redNose', 'redTips'],
    tail: 'none',
    monobody: true,
    legLength: 0.16,
    armLength: 0.22,
  },
  esper: {
    name: 'Esper',
    bodyColor: '#FF7A32',
    accentColor: '#3A1460',
    skinColor: '#FF7A32',
    limbColor: '#5C2A86',
    eyeColor: '#140818',
    mouthColor: '#FF6B8A',
    clawColor: '#3A1460',
    height: 1.06,
    belly: 1.48,
    bodyForm: 'sphere',
    limbStyle: 'spindly',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'dot',
    eyeSpacing: 0.07,
    eyeSize: 0.022,
    eyeY: 0.1,
    mouthStyle: 'bigLips',
    browStyle: 'blocks',
    features: ['bodySpikes'],
    tail: 'none',
    monobody: true,
    legLength: 0.22,
    armLength: 0.28,
  },
  gobu: {
    name: 'Gobu',
    bodyColor: '#95D098',
    accentColor: '#6CAF73',
    skinColor: '#95D098',
    limbColor: '#6CAF73',
    eyeColor: '#5E5A54',
    scleraColor: '#EFFDE6',
    mouthColor: '#FC7E8E',
    featureColor: '#6CAF73',
    height: 0.86,
    belly: 1.22,
    bodyForm: 'egg',
    limbStyle: 'stubby',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'largeWhite',
    eyeSpacing: 0.28,
    eyeSize: 0.1,
    eyeY: 0.08,
    mouthStyle: 'line',
    browStyle: 'none',
    features: ['leafSprout', 'cheekDashes', 'backBumps'],
    tail: 'spiral',
    monobody: true,
    legLength: 0.12,
    armLength: 0.14,
  },
  grompy: {
    name: 'Grompy',
    bodyColor: '#FFB1C6',
    accentColor: '#4A1548',
    skinColor: '#FFB1C6',
    limbColor: '#FFB1C6',
    eyeColor: '#3B0D3D',
    clawColor: '#4A1548',
    featureColor: '#4A1548',
    height: 1.0,
    belly: 1.28,
    bodyForm: 'pear',
    limbStyle: 'stubby',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'dot',
    eyeSpacing: 0.18,
    eyeSize: 0.03,
    eyeY: 0.16,
    mouthStyle: 'line',
    browStyle: 'thin',
    features: ['hairTuft', 'claws3', 'pawPads'],
    tail: 'none',
    monobody: true,
    legLength: 0.15,
    armLength: 0.2,
  },
  ohle: {
    name: 'Ohle',
    bodyColor: '#669999',
    accentColor: '#330066',
    skinColor: '#669999',
    limbColor: '#669999',
    eyeColor: '#000000',
    toothColor: '#F0F0EE',
    clawColor: '#330066',
    featureColor: '#558888',
    height: 0.98,
    belly: 1.2,
    bodyForm: 'bean',
    limbStyle: 'stubby',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'dot',
    eyeSpacing: 0.12,
    eyeSize: 0.028,
    eyeY: 0.1,
    mouthStyle: 'buckTeeth',
    browStyle: 'blocks',
    features: ['bunnyEars', 'hairTuft', 'claws3', 'bellySeam'],
    tail: 'ball',
    monobody: true,
    legLength: 0.1,
    armLength: 0.16,
  },
  rafog: {
    name: 'Rafog',
    bodyColor: '#E0B23A',
    accentColor: '#3D1A4A',
    skinColor: '#E0B23A',
    limbColor: '#D4A82E',
    eyeColor: '#2E6BD4',
    scleraColor: '#F4F7FF',
    clawColor: '#3D1A4A',
    featureColor: '#3D1A4A',
    mouthColor: '#3D1A4A',
    height: 1.1,
    belly: 1.32,
    bodyForm: 'pear',
    limbStyle: 'stubby',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'dot',
    eyeSpacing: 0.1,
    eyeSize: 0.026,
    eyeY: 0.14,
    mouthStyle: 'line',
    browStyle: 'thin',
    features: ['trunk', 'spiralAntenna', 'nubEars'],
    tail: 'none',
    monobody: true,
    legLength: 0.12,
    armLength: 0.16,
  },
  teewong: {
    name: 'Teewong',
    bodyColor: '#4A2468',
    accentColor: '#FF7A28',
    skinColor: '#4A2468',
    limbColor: '#FF7A28',
    eyeColor: '#2A1238',
    scleraColor: '#F6EFE6',
    irisColor: '#3B0D3D',
    toothColor: '#F7F2EA',
    featureColor: '#FF7A28',
    height: 1.04,
    belly: 1.42,
    bodyForm: 'wide',
    limbStyle: 'spindly',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'stalk',
    eyeSpacing: 0.22,
    eyeSize: 0.08,
    eyeY: 0.22,
    mouthStyle: 'oneTooth',
    browStyle: 'none',
    features: ['flameCrest'],
    tail: 'none',
    monobody: true,
    legLength: 0.14,
    armLength: 0.18,
  },
  zoem: {
    name: 'Zoem',
    bodyColor: '#99E38C',
    accentColor: '#662C67',
    skinColor: '#99E38C',
    limbColor: '#2C3047',
    eyeColor: '#1A1A1A',
    scleraColor: '#F9EB68',
    toothColor: '#FFFFFF',
    mouthColor: '#6B1A28',
    featureColor: '#99E38C',
    height: 1.22,
    belly: 1.25,
    bodyForm: 'sphere',
    limbStyle: 'longThin',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'yellow',
    eyeSpacing: 0.14,
    eyeSize: 0.07,
    eyeY: 0.06,
    mouthStyle: 'fourTeeth',
    browStyle: 'blocks',
    features: ['hairTuft'],
    tail: 'none',
    monobody: true,
    legLength: 0.4,
    armLength: 0.36,
  },
  gerarda: {
    name: 'Gerarda',
    bodyColor: '#F06C60',
    accentColor: '#5A3D82',
    skinColor: '#F06C60',
    limbColor: '#F06C60',
    eyeColor: '#000000',
    toothColor: '#FFFFFF',
    featureColor: '#F0C14A',
    height: 1.08,
    belly: 1.18,
    bodyForm: 'scurve',
    limbStyle: 'stubby',
    armCount: 2,
    eyeCount: 2,
    eyeStyle: 'dot',
    eyeSpacing: 0.1,
    eyeSize: 0.028,
    eyeY: 0.08,
    mouthStyle: 'threeTeeth',
    browStyle: 'none',
    features: ['dorsalSpikes', 'goldSpots'],
    tail: 'scurve',
    monobody: true,
    legLength: 0.12,
    armLength: 0.14,
  },
}

export const CHARACTER_ORDER: CharacterId[] = [
  'boogar',
  'ceval',
  'dan',
  'esper',
  'gobu',
  'grompy',
  'ohle',
  'rafog',
  'teewong',
  'zoem',
  'gerarda',
]
