import type { CharacterId, CharacterLook } from '../types'

export const CHARACTERS: Record<CharacterId, CharacterLook> = {
  boogar: {
    name: 'Boogar',
    bodyColor: '#8B3D9E',
    accentColor: '#E8B84A',
    skinColor: '#E8C4A8',
    height: 1.15,
    belly: 1.35,
    headShape: 'round',
    accessory: 'antenna',
  },
  ceval: {
    name: 'Ceval',
    bodyColor: '#2F8F4E',
    accentColor: '#F4E04D',
    skinColor: '#C4E8B0',
    height: 1.65,
    belly: 0.75,
    headShape: 'tall',
    accessory: 'sprout',
  },
  dan: {
    name: 'Dan',
    bodyColor: '#3D6FD9',
    accentColor: '#FF8C42',
    skinColor: '#F0C8A0',
    height: 1.35,
    belly: 0.95,
    headShape: 'round',
    accessory: 'cap',
  },
  esper: {
    name: 'Esper',
    bodyColor: '#F2C94C',
    accentColor: '#9B59B6',
    skinColor: '#FFE8B0',
    height: 1.25,
    belly: 0.85,
    headShape: 'diamond',
    accessory: 'star',
  },
  gobu: {
    name: 'Gobu',
    bodyColor: '#E67E22',
    accentColor: '#2C3E50',
    skinColor: '#D4A574',
    height: 1.05,
    belly: 1.15,
    headShape: 'wide',
    accessory: 'horns',
  },
  grompy: {
    name: 'Grompy',
    bodyColor: '#5D6D7E',
    accentColor: '#C0392B',
    skinColor: '#A89080',
    height: 1.2,
    belly: 1.45,
    headShape: 'box',
    accessory: 'unibrow',
  },
  ohle: {
    name: 'Ohle',
    bodyColor: '#FF8DC7',
    accentColor: '#FFFFFF',
    skinColor: '#FFD4E5',
    height: 1.1,
    belly: 0.9,
    headShape: 'round',
    accessory: 'bow',
  },
  rafog: {
    name: 'Rafog',
    bodyColor: '#E74C3C',
    accentColor: '#1A1A1A',
    skinColor: '#E8A87C',
    height: 1.4,
    belly: 0.88,
    headShape: 'round',
    accessory: 'mohawk',
  },
  teewong: {
    name: 'Teewong',
    bodyColor: '#1ABC9C',
    accentColor: '#F39C12',
    skinColor: '#B8E0D0',
    height: 1.3,
    belly: 0.8,
    headShape: 'oval',
    accessory: 'glasses',
  },
  zoem: {
    name: 'Zoem',
    bodyColor: '#5DADE2',
    accentColor: '#AF7AC5',
    skinColor: '#D6EAF8',
    height: 1.18,
    belly: 1.0,
    headShape: 'round',
    accessory: 'headphones',
  },
  gerarda: {
    name: 'Gerarda',
    bodyColor: '#AF7AC5',
    accentColor: '#F5B041',
    skinColor: '#F5CBA7',
    height: 1.22,
    belly: 1.2,
    headShape: 'round',
    accessory: 'bun',
  },
}

export const CHARACTER_ORDER: CharacterId[] = [
  'boogar',
  'ceval',
  'dan',
  'esper',
  'gobu',
  'grompy',
  'ohle',
  'rafog',
  'teewong',
  'zoem',
  'gerarda',
]
